# _config.yml

permalink: pretty

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true
  include:
    - "*.md"
    - "**/*.md"  # This ensures it processes nested files
