# _config.yml
defaults:
  -
    scope:
      path: "" # Applies to all files
      type: pages # Applies to pages (includes .md files)
    values:
      layout: default
# Optional: Set a default site title
title: My Site
