var entradas = [
  "▓26-05-27 - Implementación de etiquetas para campos o temas – Actividad reciente▒https://jucardus.github.io/2/6/-/26-05-27-implementacion-de-etiquetas-para-campos-o-temas▓",
  "▓26-05-27 - Limpieza en el repositorio – Actividad reciente▒https://jucardus.github.io/2/6/-/26-05-27-limpieza-en-el-repositorio▓",
  "▓26-05-27 - Mejoras en la página de busca – Actividad reciente▒https://jucardus.github.io/2/6/-/26-05-27-mejoras-en-la-pagina-de-busca▓",
  "▓26-06-02 - Mejoras significativas en la página de enlaces – Actividad reciente▒https://jucardus.github.io/2/6/-/26-06-02-mejoras-significativas-en-la-pagina-de-enlaces▓",
  "▓a lo largo de todo el año [loc.] – Diccionario multilingüe - A, Locuciones multilingües, Tmp - tiempo▒https://jucardus.github.io/a/-/l/a-lo-largo-de-todo-el-ano-loc▓",
  "▓A veces buscamos respuestas rápidas... – Citas y proverbios, Citas y proverbios - A▒https://jucardus.github.io/a/-/v/a-veces-buscamos-respuestas-rapidas▓",
  "▓abacería [f.] – Almnts - alimentos, Diccionario multilingüe - A, Estblcmnts - establecimientos, Sustantivos multilingües, Sustantivos multilingües femeninos▒https://jucardus.github.io/a/b/a/abaceria-f▓",
  "▓abacero, -ra [m.f.] – Diccionario multilingüe - A, Ofcs - oficios, Sustantivos multilingües, Sustantivos multilingües femeninos, Sustantivos multilingües masculinos▒https://jucardus.github.io/a/b/a/abacero-ra-mf▓",
  "▓abdicar [v.] – Diccionario multilingüe - A, Rlz - realeza, Verbos multilingües▒https://jucardus.github.io/a/b/d/abdicar-v▓",
  "▓abdomen [m.] – Antm - anatomía, Diccionario multilingüe - A, Sustantivos multilingües, Sustantivos multilingües masculinos▒https://jucardus.github.io/a/b/d/abdomen-m▓",
  "▓Admiro a los hombres que buscan el orden... – Citas y proverbios, Citas y proverbios - A▒https://jucardus.github.io/a/d/m/admiro-a-los-hombres-que-buscan-el-orden▓",
  "▓Adonde no pueden llegar ni tu vista... – Citas de Agustín de Hipona, Citas y proverbios, Citas y proverbios - A▒https://jucardus.github.io/a/d/o/adonde-no-pueden-llegar-ni-tu-vista▓",
  "▓afectuoso [adj.] – Adjetivos multilingües, Diccionario multilingüe - A, Tmprmnts - temperamentos▒https://jucardus.github.io/a/f/e/afectuoso-adj▓",
  "▓Al perro que tiene dinero se... – Citas y proverbios, Citas y proverbios - A, Proverbios▒https://jucardus.github.io/a/l/-/al-perro-que-tiene-dinero-se▓",
  "▓Algún día el presente... – Apotegmas▒https://jucardus.github.io/a/l/g/algun-dia-el-presente▓",
  "▓Algún día todo... – Apotegmas▒https://jucardus.github.io/a/l/g/algun-dia-todo▓",
  "▓Animales puros e impuros en el cristianismo – Cristianismo, Reflexiones▒https://jucardus.github.io/a/n/i/animales-puros-e-impuros-en-el-cristianismo▓",
  "▓Autor y contacto – Subpáginas de este sitio▒https://jucardus.github.io/a/u/t/autor-y-contacto▓",
  "▓azolvar [v.] – Verbos españoles, Vocabulario español - V▒https://jucardus.github.io/a/z/o/azolvar-v▓",
  "▓bóveda [f.] – Arqtctr - arquitectura, Diccionario multilingüe - B, Sustantivos multilingües, Sustantivos multilingües femeninos▒https://jucardus.github.io/b/o/v/boveda-f▓",
  "▓buis [m.] – Arbls - árboles, Sustantivos franceses, Sustantivos franceses masculinos, Vocabulario francés - B▒https://jucardus.github.io/b/u/i/buis-m▓",
  "▓Busca en Jucardus – Subpáginas de este sitio▒https://jucardus.github.io/b/u/s/busca-en-jucardus▓",
  "▓Buscamos a Dios porque hemos dejado de creer... – Apotegmas▒https://jucardus.github.io/b/u/s/buscamos-a-dios-porque-hemos-dejado-de-creer▓",
  "▓cabeza de familia [m.f.c.] – Diccionario multilingüe - C, Fml - familia, Grrqs - gerarquías, Sustantivos multilingües compuestos, Sustantivos multilingües femeninos, Sustantivos multilingües masculinos▒https://jucardus.github.io/c/a/b/cabeza-de-familia-mfc▓",
  "▓caillouteux [adj.] – Adjetivos franceses, Vocabulario francés - C▒https://jucardus.github.io/c/a/i/caillouteux-adj▓",
  "▓cast candle [s.c.] – Sustantivos compuestos ingleses, Vls - velas, Vocabulario inglés - C▒https://jucardus.github.io/c/a/s/cast-candle-sc▓",
  "▓Categorías gramaticales – Abreviaturas de los diccionarios▒https://jucardus.github.io/c/a/t/categorias-gramaticales▓",
  "▓Citas y proverbios – Índices de este sitio▒https://jucardus.github.io/c/i/t/citas-y-proverbios▓",
  "▓cloître [m.] – Sustantivos franceses, Sustantivos franceses masculinos, Vocabulario francés - C▒https://jucardus.github.io/c/l/o/cloitre-m▓",
  "▓clou [m.] – Sustantivos franceses, Sustantivos franceses masculinos, Vocabulario francés - C▒https://jucardus.github.io/c/l/o/clou-m▓",
  "▓croisée [f.] – Sustantivos franceses, Sustantivos franceses femeninos, Vocabulario francés - C▒https://jucardus.github.io/c/r/o/croisee-f▓",
  "▓Cuando exponer un delito es tratado como... – Citas y proverbios, Citas y proverbios - C▒https://jucardus.github.io/c/u/a/cuando-exponer-un-delito-es-tratado-como▓",
  "▓Cuanto menos talento tienen, más orgullo... – Citas y proverbios, Citas y proverbios - C▒https://jucardus.github.io/c/u/a/cuanto-menos-talento-tienen-mas-orgullo▓",
  "▓De la circularidad de la religión te... – Apotegmas▒https://jucardus.github.io/d/e/-/de-la-circularidad-de-la-religion-te▓",
  "▓Después de meses, vi a una persona leyendo... – Reflexiones▒https://jucardus.github.io/d/e/s/despues-de-meses-vi-a-una-persona-leyendo▓",
  "▓destreza [f.] – Diccionario multilingüe - D, Sustantivos multilingües, Sustantivos multilingües femeninos▒https://jucardus.github.io/d/e/s/destreza-f▓",
  "▓devanture [f.] – Sustantivos franceses, Sustantivos franceses femeninos, Vocabulario francés - D▒https://jucardus.github.io/d/e/v/devanture-f▓",
  "▓Diccionario multilingüe – Índices de este sitio▒https://jucardus.github.io/d/i/c/diccionario-multilingue▓",
  "▓Disculpen si les llamo caballeros, pero... – Citas de Groucho Marx, Citas y proverbios, Citas y proverbios - D▒https://jucardus.github.io/d/i/s/disculpen-si-les-llamo-caballeros-pero▓",
  "▓El destino del hombre está... – Citas y proverbios, Citas y proverbios - E▒https://jucardus.github.io/e/l/-/el-destino-del-hombre-esta▓",
  "▓El destino es el que baraja las cartas... – Citas de Shakespeare, Citas y proverbios, Citas y proverbios - E▒https://jucardus.github.io/e/l/-/el-destino-es-el-que-baraja-las-cartas▓",
  "▓El dolor y el sufrimiento son siempre inevitables... – Citas de Dostoyevski, Citas y proverbios, Citas y proverbios - E▒https://jucardus.github.io/e/l/-/el-dolor-y-el-sufrimiento-son-siempre-inevitables▓",
  "▓El Estado es una banda de ladrones... – Citas y proverbios, Citas y proverbios - E▒https://jucardus.github.io/e/l/-/el-estado-es-una-banda-de-ladrones▓",
  "▓El filósofo es un hombre que no quiere creer... – Citas y proverbios, Citas y proverbios - E▒https://jucardus.github.io/e/l/-/el-filosofo-es-un-hombre-que-no-quiere-creer▓",
  "▓El hombre está condenado... – Citas y proverbios, Citas y proverbios - E▒https://jucardus.github.io/e/l/-/el-hombre-esta-condenado▓",
  "▓El hombre muere en todos aquellos... – Citas y proverbios, Citas y proverbios - E▒https://jucardus.github.io/e/l/-/el-hombre-muere-en-todos-aquellos▓",
  "▓El hombre que tiene miedo sin peligro... – Citas y proverbios, Citas y proverbios - E▒https://jucardus.github.io/e/l/-/el-hombre-que-tiene-miedo-sin-peligro▓",
  "▓El hombre, un ejemplo de la... – Citas y proverbios, Citas y proverbios - E▒https://jucardus.github.io/e/l/-/el-hombre-un-ejemplo-de-la▓",
  "▓El igualitarismo crea la desigualdad más... – Citas de Thomas Sowell, Citas y proverbios, Citas y proverbios - E▒https://jucardus.github.io/e/l/-/el-igualitarismo-crea-la-desigualdad-mas▓",
  "▓El mayor castigo para quienes no se interesan... – Citas y proverbios, Citas y proverbios - E▒https://jucardus.github.io/e/l/-/el-mayor-castigo-para-quienes-no-se-interesan▓",
  "▓El mayor consuelo para los fanáticos es... – Citas y proverbios, Citas y proverbios - E▒https://jucardus.github.io/e/l/-/el-mayor-consuelo-para-los-fanaticos-es▓",
  "▓El oro es como las mujeres, que todos... – Citas de Lope de Vega, Citas y proverbios, Citas y proverbios - E▒https://jucardus.github.io/e/l/-/el-oro-es-como-las-mujeres-que-todos▓",
  "▓El pensamiento es la semilla... – Citas y proverbios, Citas y proverbios - E▒https://jucardus.github.io/e/l/-/el-pensamiento-es-la-semilla▓",
  "▓El poeta es... – Citas y proverbios, Citas y proverbios - E▒https://jucardus.github.io/e/l/-/el-poeta-es▓",
  "▓El político debe ser capaz de predecir... – Citas de Winston Churchill, Citas y proverbios, Citas y proverbios - E▒https://jucardus.github.io/e/l/-/el-politico-debe-ser-capaz-de-predecir▓",
  "▓El primer método para evaluar la inteligencia... – Citas de Maquiavelo, Citas y proverbios, Citas y proverbios - E▒https://jucardus.github.io/e/l/-/el-primer-metodo-para-evaluar-la-inteligencia▓",
  "▓El progreso no es un accidente... – Citas y proverbios, Citas y proverbios - E▒https://jucardus.github.io/e/l/-/el-progreso-no-es-un-accidente▓",
  "▓El propósito de elegir funcionarios es... – Citas y proverbios, Citas y proverbios - E▒https://jucardus.github.io/e/l/-/el-proposito-de-elegir-funcionarios-es▓",
  "▓emmet [s.] – Entmlg - entomología, Sustantivos ingleses, Vocabulario inglés - E▒https://jucardus.github.io/e/m/m/emmet-s▓",
  "▓en un abrir y cerrar de ojos [loc.] – Diccionario multilingüe - E, Locuciones multilingües▒https://jucardus.github.io/e/n/-/en-un-abrir-y-cerrar-de-ojos-loc▓",
  "▓Enlaces varios – Subpáginas de este sitio▒https://jucardus.github.io/e/n/l/enlaces-varios▓",
  "▓Entradas recientes – Subpáginas de este sitio▒https://jucardus.github.io/e/n/t/entradas-recientes▓",
  "▓Etiquetas de los diccionarios – Abreviaturas de los diccionarios▒https://jucardus.github.io/e/t/i/etiquetas-de-los-diccionarios▓",
  "▓fila [f.] – Diccionario multilingüe - F, Sustantivos multilingües, Sustantivos multilingües femeninos▒https://jucardus.github.io/f/i/l/fila-f▓",
  "▓Frases chinas desglosadas – Índices de este sitio▒https://jucardus.github.io/f/r/a/frases-chinas-desglosadas▓",
  "▓iletrado, -da [adj.] – Adjetivos multilingües, Diccionario multilingüe - I▒https://jucardus.github.io/i/l/e/iletrado-da-adj▓",
  "▓Índices alfabéticos – Índices de este sitio, Subpáginas de este sitio▒https://jucardus.github.io/i/n/d/indices-alfabeticos▓",
  "▓inhabité [adj.] – Adjetivos franceses, Vocabulario francés - I▒https://jucardus.github.io/i/n/h/inhabite-adj▓",
  "▓inquiry [s.] – Sustantivos ingleses, Vocabulario inglés - I▒https://jucardus.github.io/i/n/q/inquiry-s▓",
  "▓La técnica de mostrar la otra mejilla... – Apotegmas▒https://jucardus.github.io/l/a/-/la-tecnica-de-mostrar-la-otra-mejilla▓",
  "▓ligueur, -euse [m.f.] – Sustantivos franceses, Sustantivos franceses femeninos, Sustantivos franceses masculinos, Vocabulario francés - L▒https://jucardus.github.io/l/i/g/ligueur-euse-mf▓",
  "▓logis [m.] – Sustantivos franceses, Sustantivos franceses masculinos, Vocabulario francés - L▒https://jucardus.github.io/l/o/g/logis-m▓",
  "▓Los viejos tiempos nunca vuelven, porque... – Apotegmas▒https://jucardus.github.io/l/o/s/los-viejos-tiempos-nunca-vuelven-porque▓",
  "▓many-sided [adj.c.] – Adjetivos compuestos ingleses, Vocabulario inglés - M▒https://jucardus.github.io/m/a/n/many-sided-adjc▓",
  "▓minnow [s.] – Ictlg - ictiología, Psc - pesca, Sustantivos ingleses, Vocabulario inglés - M▒https://jucardus.github.io/m/i/n/minnow-s▓",
  "▓noblesse de cloche [f.c.] – Nblz - nobleza, Sustantivos franceses compuestos, Sustantivos franceses femeninos, Vocabulario francés - N▒https://jucardus.github.io/n/o/b/noblesse-de-cloche-fc▓",
  "▓œillet [m.] – Flrs - flores, Sustantivos franceses, Sustantivos franceses masculinos, Vocabulario francés - O▒https://jucardus.github.io/o/e/i/oeillet-m▓",
  "▓ouvrouère [m.] – Sustantivos franceses, Sustantivos franceses masculinos, Vocabulario francés - O▒https://jucardus.github.io/o/u/v/ouvrouere-m▓",
  "▓plead [v.] – Verbos ingleses, Vocabulario inglés - P▒https://jucardus.github.io/p/l/e/plead-v▓",
  "▓plein-cintre [m.c.] – Sustantivos franceses, Sustantivos franceses compuestos, Sustantivos franceses masculinos, Vocabulario francés - P▒https://jucardus.github.io/p/l/e/plein-cintre-mc▓",
  "▓pretender [v.] – Diccionario multilingüe - P, Verbos multilingües▒https://jucardus.github.io/p/r/e/pretender-v▓",
  "▓Pronto tendremos casas completas de plásticos... – Reflexiones▒https://jucardus.github.io/p/r/o/pronto-tendremos-casas-completas-de-plasticos▓",
  "▓purport [v.] – Verbos ingleses, Vocabulario inglés - P▒https://jucardus.github.io/p/u/r/purport-v▓",
  "▓quagmire [s.] – Sustantivos ingleses, Vocabulario inglés - Q▒https://jucardus.github.io/q/u/a/quagmire-s▓",
  "▓quoique [conj.] – Conjunciones francesas, Vocabulario francés - Q▒https://jucardus.github.io/q/u/o/quoique-conj▓",
  "▓rephrase [v.] – Diccionario inglés-español - R, Rtrc - retórica, Verbos ingleses▒https://jucardus.github.io/r/e/p/rephrase-v▓",
  "▓rez-de-chaussée [m.c.] – Arqtctr - arquitectura, Sustantivos franceses, Sustantivos franceses compuestos, Sustantivos franceses masculinos, Vocabulario francés - R▒https://jucardus.github.io/r/e/z/rez-de-chaussee-mc▓",
  "▓sagacidad [f.] – Diccionario multilingüe - S, Sustantivos femeninos multilingües▒https://jucardus.github.io/s/a/g/sagacidad-f▓",
  "▓scrape [s.] – Sustantivos ingleses, Vocabulario inglés - S▒https://jucardus.github.io/s/c/r/scrape-s▓",
  "▓set up [v.c.] – Verbos compuestos ingleses, Vocabulario inglés - S▒https://jucardus.github.io/s/e/t/set-up-vc▓",
  "▓shrewdness [s.] – Sustantivos ingleses, Vocabulario inglés - S▒https://jucardus.github.io/s/h/r/shrewdness-s▓",
  "▓Si quieres saber quién te controla... – Citas de Voltaire, Citas y proverbios, Citas y proverbios - S▒https://jucardus.github.io/s/i/-/si-quieres-saber-quien-te-controla▓",
  "▓Sí. Una de las condiciones para que la democracia... – Reflexiones▒https://jucardus.github.io/s/i/-/si-una-de-las-condiciones-para-que-la-democracia▓",
  "▓Siempre hay alguien orando por ti – Reflexiones▒https://jucardus.github.io/s/i/e/siempre-hay-alguien-orando-por-ti▓",
  "▓Son demasiados los presupuestos para poner... – Reflexiones▒https://jucardus.github.io/s/o/n/son-demasiados-los-presupuestos-para-poner▓",
  "▓tallow-chandler [s.c.] – Sustantivos compuestos ingleses, Vocabulario inglés - T▒https://jucardus.github.io/t/a/l/tallow-chandler-sc▓",
  "▓Tareas pendientes – Tareas pendientes▒https://jucardus.github.io/t/a/r/tareas-pendientes▓",
  "▓terse style [s.c.] – EstlsLtrrs - estilos literarios, Sustantivos compuestos ingleses, Vocabulario inglés - T▒https://jucardus.github.io/t/e/r/terse-style-sc▓",
  "▓Todas las etiquetas – Índices de este sitio, Subpáginas de este sitio▒https://jucardus.github.io/t/o/d/todas-las-etiquetas▓",
  "▓toit en colombage [m.c.] – Arqtctr - arquitectura, Sustantivos compuestos franceses, Sustantivos franceses, Sustantivos franceses masculinos, Vocabulario francés - T▒https://jucardus.github.io/t/o/i/toit-en-colombage-mc▓",
  "▓Una nación de ovejas... – Citas y proverbios, Citas y proverbios - U▒https://jucardus.github.io/u/n/a/una-nacion-de-ovejas▓",
  "▓Vocabulario francés – Índices de este sitio▒https://jucardus.github.io/v/o/c/vocabulario-frances▓",
  "▓Vocabulario inglés – Índices de este sitio▒https://jucardus.github.io/v/o/c/vocabulario-ingles▓",
  "▓voûte [f.] – Arqtctr - arquitectura, Sustantivos franceses, Sustantivos franceses femeninos, Vocabulario francés - V▒https://jucardus.github.io/v/o/u/voute-f▓",
  "▓wharf [s.] – Notas gramaticales inglesas, Plurales irregulares ingleses, Sustantivos ingleses, Vocabulario inglés - W▒https://jucardus.github.io/w/h/a/wharf-s▓",
  "▓wick [s.] – Sustantivos ingleses, Vocabulario inglés - W▒https://jucardus.github.io/w/i/c/wick-s▓",
  "▓withal [adv.] – Adverbios ingleses, Vocabulario inglés - W▒https://jucardus.github.io/w/i/t/withal-adv▓",
  "▓他自稱是這封信的作者。 – Frases chinas desglosadas▒https://jucardus.github.io/2/0/1/他自稱是這封信的作者▓",
  "▓她自稱從未犯過錯。 – Frases chinas desglosadas▒https://jucardus.github.io/2/2/9/她自稱從未犯過錯▓",
  "▓沒有人自稱完美。 – Frases chinas desglosadas▒https://jucardus.github.io/2/7/7/沒有人自稱完美▓"
];