let data = [
"autógrafo [adj.] // Que está escrito de mano de su mismo autor.",
"antónimo de «autógrafo» // ológrafo, hológrafo",
"apógrafo [m.] // Copia de un manuscrito original.",
"咖啡 // [kāfēi] café",
"ubérrimo [adj.] // Muy fértil y abundante.",
"sinónimos de «ubérrimo» // fértil, fecundo, prolífico, productivo, feraz, abundante",
"sicalipsis [f.] // Malicia sexual, picardía erótica.",
"tartufo [m.] // Hombre hipócrita y falso.",
"較 (较) // [jiào] comparar, contrastar; disputar",
"epistemología [f.] // Teoría de los fundamentos y métodos del conocimiento científico.",
"喜歡 (喜欢) // [xǐhuān] gustar, disfrutar, tener afición por, preferir",
"老師 (老师) // [lǎoshī] profesor, maestro, instructor",
"trailer [s.] // avance (de una película)",
"reconcomio [m.] 1 // Desasosiego o agitación por un picor o comezón.",
"reconcomio [m.] 2 // Desasosiego o agitación por una molestia moral o por un deseo persistente.",
"a oscuras [loc.] In. - Es. // in the dark; in darkness",
"天氣 (天气) // [tiānqì] clima, tiempo",
"冷 // [lěng] frío, indiferente, poco amistoso",
"reconcomio [m.] Es. In. // nagging regret, gnawing feeling, lingering guilt, persistent unease, resentment",
"afforestation [n.] // the act or process of establishing a forest especially on land not previously forested",
"棵 // [kē] (clasificador para árboles y plantas)",
"喜 // [xǐ] suceso alegre, embarazo, aficionado a, felicidad, deleite",
"dado [m.] Es. La. // alea, tessera",
"骰子 // [tóuzi] dados",
"骨 // [gǔ ㄍㄨˇ] hueso, esqueleto; carácter, espíritu",
"Aleae in mensa sunt. // [ˈa.le.ai̯ in ˈmen.sa sunt] The dice are on the table. ¶ Aleae: Nominative plural, subject of the sentence ([ˈa.le.ai̯]). ¶ in mensa: Prepositional phrase meaning 'on the table' (ablative for location). ¶ sunt: Third-person plural of 'to be' ([sunt]).",
"Tesserae ludum faciunt. // [ˈtes.se.rai̯ ˈluː.dum ˈfa.ki.unt] The dice make the game. ¶ Tesserae: Nominative plural, subject of the sentence ([ˈtes.se.rai̯]). ¶ ludum: Accusative singular of ludus (game), direct object. ¶ faciunt: Third-person plural of facere (to make/do) ([ˈfa.ki.unt]).",
"Aleae et tesserae in villa iactantur. // [ˈa.le.ai̯ et ˈtes.se.rai̯ in ˈwil.la jakˈtan.tur] The dice are thrown in the villa. ¶ Aleae et tesserae: Nominative plural, compound subject ([ˈa.le.ai̯] and [ˈtes.se.rai̯]). ¶ in villa: Prepositional phrase meaning 'in the villa' (ablative for location). ¶ iactantur: Third-person plural present passive of iactare (to throw), indicating the dice are being thrown ([jakˈtan.tur]).",
"Tenir le dé de la conversation // dominer la conversation, accaparer la parole.",
"Ego aleam iacto. // [ˈe.ɡo ˈa.le.am ˈjak.to] I throw the die. ¶ aleam: Accusative singular, direct object of iacto ('I throw'). ¶ ego: Nominative pronoun 'I' for emphasis (optional in Latin). ¶ iacto: First-person singular present indicative of iactare ('to throw').",
"Pueri aleās in villa spectant. // [ˈpu.e.ri ˈa.le.aːs in ˈwil.la ˈspek.tant] The boys watch the dice in the villa. ¶ aleās: Accusative plural, direct object of spectant ('they watch'). ¶ pueri: Nominative plural of puer ('boy'), subject. ¶ in villa: Ablative phrase indicating location ('in the villa'). ¶ spectant: Third-person plural present indicative of spectare ('to watch').",
"Ludus aleam desiderat. // [ˈluː.dus ˈa.le.am de.siˈde.rat] The game requires a die. ¶ Accusative singular, direct object of desiderat ('it requires'). ¶ ludus: Nominative singular ('game'), subject. ¶ desiderat: Third-person singular present indicative of desiderare ('to desire/require').",
"Ego aleam desidero. // [ˈe.ɡo ˈa.le.am de.siˈde.ro] I desire a die. ¶ aleam: Accusative singular, direct object of desidero. ¶ ego: Nominative pronoun 'I' for emphasis (optional). ¶ desidero: First-person singular present indicative active of desiderare ('I desire').",
"Nos aleās desideramus. // [noːs ˈa.le.aːs de.si.deˈraː.mus] We desire the dice. ¶ aleās: Accusative plural, direct object of desideramus. ¶ nos: Nominative pronoun 'we' for emphasis. ¶ desideramus: First-person plural present indicative active of desiderare ('we desire').",
"Puer aleam in villa desiderat. // [ˈpu.er ˈa.le.am in ˈwil.la de.siˈde.rat] The boy desires a die in the villa. ¶ aleam: Accusative singular, direct object of desiderat. ¶ puer: Nominative singular ('boy'), subject. ¶ in villa: Ablative phrase indicating location ('in the villa'). ¶ desiderat: Third-person singular present indicative active of desiderare ('he desires').",
"Aleās desiderata voco. // [ˈa.le.aːs de.si.deˈraː.ta ˈwo.ko] I call the dice 'things desired.' ¶ Here, desiderata (neuter plural accusative) describes aleās as objects of desire.",
"Ego aleās multum amo, sed aleam nolo. // [ˈe.ɡo ˈa.le.aːs ˈmul.tum ˈa.mo | sed ˈa.le.am ˈnoː.lo] I like dice a lot, but I don't like gambling. ¶ aleās ([ˈa.le.aːs]): Accusative plural of alea ('dice'), direct object of amo. ¶ amo ([ˈa.mo]): First-person singular present indicative of amare. ¶ sed ([sed]): Conjunction meaning 'but'. ¶ aleam ([ˈa.le.am]): Accusative singular of alea, here used to mean 'gambling' or 'game of chance.' ¶ nolo ([ˈnoː.lo]): First-person singular present indicative of nolle ('to not want' or 'to not like'). Nolo is a stronger expression of disliking or refusing something in Latin, suitable here to contrast with amo.",
"dado (multilingüe) // AL. Würfel -s; - [m.] ¶ CH. 骰子 [tóuzi] ¶ FR. Dé [m.] ¶ IT. Dado [m.] ¶ LA. alea, tessera",
"amāre (presente indicativo v. latino) // ego amo; tu amas; is/ea/id amat; nos amamus; vos amatis; ei/eae/ea amant",
"amāre (La. Es.) // amar, gustar (gustar mucho de algo), tener afición por",
"這 (这) // [zhè] este, esta, esto; así (en este sentido)",
"這是一棵樹。 (这是一棵树。) // [Zhè shì yī kē shù.] Esto es un árbol.",
"Deus est. // Dios existe.",
"Ego labōrō. // [ˈɛ.ɡo laˈboː.roː] Yo trabajo. ¶ ego: pronombre personal en primera persona singular en caso nominativo: yo ¶ labōrō: primera persona singular del presente de indicativo del verbo _labōrāre_: trabajo"
];
