let entriesBase = [
  "▓Actividad reciente en Jucardus▒readme.md▓",
  "▓abacus [s.]▒a/b/a/abacus-s.md▓",
  "▓Actividad reciente▒actividad.md▓",
  "▓Actualización de Google Chrome con Bash▒a/c/t/actualizacion-de-google-chrome-con-bash.md▓",
  "▓Actualización de Linux Mint con Bash▒a/c/t/actualizacion-de-linux-mint-con-bash.md▓",
  "▓Actualización del navegador Brave con Bash▒a/c/t/actualizacion-del-navegador-brave-con-bash.md▓",
  "▓Ahórrate el engorroso trámite de ir a alguno...▒a/h/o/ahorrate-el-engorroso-tramite-de-ir.md▓",
  "▓amāre [v.]▒a/m/a/amare-v.md▓",
  "▓amāre [v.] · Congujación▒a/m/a/amare-v.md#congujaci%C3%B3n▓",
  "▓amāre [v.] · Presente indicativo▒a/m/a/amare-v.md#presente-indicativo▓",
  "▓amāre [v.] · Traducciones▒a/m/a/amare-v.md#traducciones▓",
  "▓Apotegmas▒a/p/apotegmas.md▓",
  "▓Bash▒b/a/bash.md▓",
  "▓Brave▒b/r/brave.md▓",
  "▓cantāre [v.]▒c/a/n/cantare-v.md▓",
  "▓cantāre [v.] · Conjugación▒c/a/n/cantare-v.md#conjugaci%C3%B3n▓",
  "▓cantāre [v.] · Frases de ejemplo▒c/a/n/cantare-v.md#frases-de-ejemplo▓",
  "▓cantāre [v.] · Presente indicativo▒c/a/n/cantare-v.md#presente-indicativo▓",
  "▓cantāre [v.] · Traducciones▒c/a/n/cantare-v.md#traducciones▓",
  "▓Caracteres chinos▒c/a/caracteres-chinos.md▓",
  "▓Catolicismo▒c/a/catolicismo.md▓",
  "▓Citas▒c/i/citas.md▓",
  "▓Clasificadores chinos▒c/l/clasificadores-chinos.md▓",
  "▓Códigos QR (enlaces)▒c/o/codigos-qr-enlaces.md▓",
  "▓códigos QR ¦ en QuickChart con leyenda▒c/o/d/codigos-qr-en-quickchart-con-leyenda.md▓",
  "▓Conjugaciones latinas▒c/o/conjugaciones-latinas.md▓",
  "▓Diccionario chino-español▒d/i/diccionario-chino-espanol.md▓",
  "▓Diccionario inglés-español▒d/i/diccionario-ingles-espanol.md▓",
  "▓Diccionario latín-español▒d/i/diccionario-latin-espanol.md▓",
  "▓Ego amō.▒e/g/o/ego-amo.md▓",
  "▓Ego amō. · Desglose▒e/g/o/ego-amo.md#desglose▓",
  "▓Ego labōrō.▒e/g/o/ego-laboro.md▓",
  "▓Ego labōrō. · Desglose▒e/g/o/ego-laboro.md#desglose▓",
  "▓Ego puerum video.▒e/g/o/ego-puerum-video.md▓",
  "▓Ego puerum video. · Desglose▒e/g/o/ego-puerum-video.md#desglose▓",
  "▓Ego sum.▒e/g/o/ego-sum.md▓",
  "▓Ego sum. · Desglose▒e/g/o/ego-sum.md#desglose▓",
  "▓El castigo del mentiroso no es que...▒e/l/c/el-castigo-del-mentiroso-no-es-que.md▓",
  "▓El recuerdo más puro▒e/l/r/el-recuerdo-mas-puro.md▓",
  "▓El universo todo confabula para que...▒e/l/u/el-universo-todo-confabula-para-que.md▓",
  "▓Enlaces varios▒e/n/enlaces-varios.md▓",
  "▓Es inevitable usar el raciocinio al...▒e/s/i/es-inevitable-usar-el-raciocinio-al.md▓",
  "▓Etiquetas todas▒etiquetas.md▓",
  "▓Fēmina ambulat.▒f/e/m/femina-ambulat.md▓",
  "▓Fēmina ambulat. · Desglose▒f/e/m/femina-ambulat.md#desglose▓",
  "▓Frases chinas▒f/r/frases-chinas.md▓",
  "▓Frases latinas▒f/r/frases-latinas.md▓",
  "▓Frases multilingües▒f/r/frases-multilingves.md▓",
  "▓GitHub▒g/i/github.md▓",
  "▓GitHub ¦ GitHub Browser Extensions▒g/i/t/github-github-browser-extensions.md▓",
  "▓GitHub Repository Traffic Tracking Overview▒g/i/t/github-repository-traffic-tracking-overview.md▓",
  "▓GitHub Repository Traffic Tracking Overview · Example from User Reports▒g/i/t/github-repository-traffic-tracking-overview.md#example-from-user-reports▓",
  "▓GitHub Repository Traffic Tracking Overview · GitHub Repository Traffic Tracking Overview▒g/i/t/github-repository-traffic-tracking-overview.md#github-repository-traffic-tracking-overview▓",
  "▓GitHub Repository Traffic Tracking Overview · How Visit Counts Work in Repository Traffic▒g/i/t/github-repository-traffic-tracking-overview.md#how-visit-counts-work-in-repository-traffic▓",
  "▓GitHub Repository Traffic Tracking Overview · Key Distinction: Repository Traffic vs. Pages Site Traffic▒g/i/t/github-repository-traffic-tracking-overview.md#key-distinction%3A-repository-traffic-vs.-pages-site-traffic▓",
  "▓GitHub Repository Traffic Tracking Overview · Limitations and Tips▒g/i/t/github-repository-traffic-tracking-overview.md#limitations-and-tips▓",
  "▓Google Chrome▒g/o/google-chrome.md▓",
  "▓Gramática china▒g/r/gramatica-china.md▓",
  "▓Gramática latina▒g/r/gramatica-latina.md▓",
  "▓Ille amat.▒i/l/l/ille-amat.md▓",
  "▓Ille amat. · Desglose▒i/l/l/ille-amat.md#desglose▓",
  "▓Índice alfabético▒indice.md▓",
  "▓Jucardus punto com▒index.md▓",
  "▓Jucardus punto com · Autor y contacto▒index.md#autor-y-contacto▓",
  "▓Jucardus punto com · Mis sitios web▒index.md#mis-sitios-web▓",
  "▓La fe te salva de la circularidad...▒l/a/f/la-fe-te-salva-de-la-circularidad.md▓",
  "▓La realidad siempre supera a la ficción...▒l/a/r/la-realidad-siempre-supera-a-la-ficcion.md▓",
  "▓La Verdad existe desde siempre▒l/a/v/la-verdad-existe-desde-siempre.md▓",
  "▓Linux Mint▒l/i/linux-mint.md▓",
  "▓merienda [sin.]▒m/e/r/merienda-sin.md▓",
  "▓Mira hacia arriba para idolatrar▒m/i/r/mira-hacia-arriba-para-idolatrar.md▓",
  "▓No hay forma de creer en Dios si no es...▒n/o/h/no-hay-forma-de-creer-en-dios.md▓",
  "▓Page Not Found▒404_backup.md▓",
  "▓Plugins▒p/l/plugins.md▓",
  "▓Plugins para GitHub▒p/l/plugins-para-github.md▓",
  "▓Programación▒p/r/programacion.md▓",
  "▓Pronombres chinos▒p/r/pronombres-chinos.md▓",
  "▓Pronombres latinos▒p/r/pronombres-latinos.md▓",
  "▓Pronombres personales latinos▒p/r/o/pronombres-personales-latinos.md▓",
  "▓Pronombres personales latinos · Primera persona, singular / plural▒p/r/o/pronombres-personales-latinos.md#primera-persona%2C-singular-%2F-plural▓",
  "▓Pronombres personales latinos · Segunda persona, singular / plural▒p/r/o/pronombres-personales-latinos.md#segunda-persona%2C-singular-%2F-plural▓",
  "▓Pronombres personales latinos · Tercera persona, forma femenina, singular / plural▒p/r/o/pronombres-personales-latinos.md#tercera-persona%2C-forma-femenina%2C-singular-%2F-plural▓",
  "▓Pronombres personales latinos · Tercera persona, forma masculina, singular / plural▒p/r/o/pronombres-personales-latinos.md#tercera-persona%2C-forma-masculina%2C-singular-%2F-plural▓",
  "▓Pronombres personales latinos · Tercera persona, forma neutra, singular / plural▒p/r/o/pronombres-personales-latinos.md#tercera-persona%2C-forma-neutra%2C-singular-%2F-plural▓",
  "▓puer [m.]▒p/u/e/puer-m.md▓",
  "▓puer [m.] · Declinación▒p/u/e/puer-m.md#declinaci%C3%B3n▓",
  "▓puer [m.] · Frases de ejemplo▒p/u/e/puer-m.md#frases-de-ejemplo▓",
  "▓puer [m.] · Traducciones▒p/u/e/puer-m.md#traducciones▓",
  "▓Puer cantat.▒p/u/e/puer-cantat.md▓",
  "▓Puer cantat. · Desglose▒p/u/e/puer-cantat.md#desglose▓",
  "▓Que tu única identidad, si acaso...▒q/u/e/que-tu-unica-identidad-si-acaso.md▓",
  "▓Según Grok▒s/e/segun-grok.md▓",
  "▓Sinónimos españoles▒s/i/sinonimos-espanoles.md▓",
  "▓Sustantivos ingleses▒s/u/sustantivos-ingleses.md▓",
  "▓Sustantivos latinos▒s/u/sustantivos-latinos.md▓",
  "▓Sustantivos latinos de la segunda declinación▒s/u/sustantivos-latinos-de-la-segunda-declinacion.md▓",
  "▓Te gusta el café, ¿verdad?▒t/e/g/te-gusta-el-cafe-verdad.md▓",
  "▓The jekyll-relative-links plugin▒t/h/e/the-jekyll-relative-links-plugin.md▓",
  "▓The jekyll-relative-links plugin · Installation▒t/h/e/the-jekyll-relative-links-plugin.md#installation▓",
  "▓The jekyll-relative-links plugin · Key Features▒t/h/e/the-jekyll-relative-links-plugin.md#key-features▓",
  "▓The jekyll-relative-links plugin · Limitations and Notes▒t/h/e/the-jekyll-relative-links-plugin.md#limitations-and-notes▓",
  "▓The jekyll-relative-links plugin · Overview▒t/h/e/the-jekyll-relative-links-plugin.md#overview▓",
  "▓The jekyll-relative-links plugin · Recent Updates▒t/h/e/the-jekyll-relative-links-plugin.md#recent-updates▓",
  "▓The jekyll-relative-links plugin · Usage Examples▒t/h/e/the-jekyll-relative-links-plugin.md#usage-examples▓",
  "▓The priestly confession in the Catholic Church▒t/h/e/the-priestly-confession-in-the-catholic-church.md▓",
  "▓The priestly confession in the Catholic Church · Development of Private Confession (4th–7th Centuries)▒t/h/e/the-priestly-confession-in-the-catholic-church.md#development-of-private-confession-(4th%E2%80%937th-centuries)▓",
  "▓The priestly confession in the Catholic Church · Early Christianity (1st–3rd Centuries)▒t/h/e/the-priestly-confession-in-the-catholic-church.md#early-christianity-(1st%E2%80%933rd-centuries)▓",
  "▓The priestly confession in the Catholic Church · Formalization of the Sacrament (8th–13th Centuries)▒t/h/e/the-priestly-confession-in-the-catholic-church.md#formalization-of-the-sacrament-(8th%E2%80%9313th-centuries)▓",
  "▓The priestly confession in the Catholic Church · Key Features of Confession Today▒t/h/e/the-priestly-confession-in-the-catholic-church.md#key-features-of-confession-today▓",
  "▓The priestly confession in the Catholic Church · Middle Ages to Reformation (13th–16th Centuries)▒t/h/e/the-priestly-confession-in-the-catholic-church.md#middle-ages-to-reformation-(13th%E2%80%9316th-centuries)▓",
  "▓The priestly confession in the Catholic Church · Modern Era (17th Century–Present)▒t/h/e/the-priestly-confession-in-the-catholic-church.md#modern-era-(17th-century%E2%80%93present)▓",
  "▓Verbos latinos de la primera conjugación▒v/e/verbos-latinos-de-la-primera-conjugacion.md▓",
  "▓Vocabulario español▒v/o/vocabulario-espanol.md▓",
  "▓Vocabulario español (enlaces)▒v/o/vocabulario-espanol-enlaces.md▓",
  "▓vocabulario español ¦ patulea▒v/o/c/vocabulario-espanol-patulea.md▓",
  "▓vocabulario español ¦ patullar▒v/o/c/vocabulario-espanol-patullar.md▓",
  "▓vocabulario español ¦ truculento▒v/o/c/vocabulario-espanol-truculento.md▓",
  "▓Vocabulario inglés▒v/o/vocabulario-ingles.md▓",
  "▓Vocabulario inglés (enlaces)▒v/o/vocabulario-ingles-enlaces.md▓",
  "▓vocabulario inglés ¦ chalice▒v/o/c/vocabulario-ingles-chalice.md▓",
  "▓vocabulario inglés ¦ jaggery▒v/o/c/vocabulario-ingles-jaggery.md▓",
  "▓vocabulario inglés ¦ scathing▒v/o/c/vocabulario-ingles-scathing.md▓",
  "▓vocabulario inglés ¦ truculent▒v/o/c/vocabulario-ingles-truculent.md▓",
  "▓你 (你) [nǐ]▒n/i/3/ni3-20320.md▓",
  "▓你 (你) [nǐ] · Frases de ejemplo▒n/i/3/ni3-20320.md#frases-de-ejemplo▓",
  "▓你 (你) [nǐ] · Traducciones▒n/i/3/ni3-20320.md#traducciones▓",
  "▓你喜歡咖啡，是不是？▒n/i/3/ni3-xi3-huan1-ka1-fei1-shi4-bu2-shi4.md▓",
  "▓你喜歡咖啡，是不是？ · Desglose▒n/i/3/ni3-xi3-huan1-ka1-fei1-shi4-bu2-shi4.md#desglose▓",
  "▓冷 (冷) [lěng]▒l/e/n/leng3-20919.md▓",
  "▓冷 (冷) [lěng] · Frases de ejemplo▒l/e/n/leng3-20919.md#frases-de-ejemplo▓",
  "▓冷 (冷) [lěng] · Traducciones▒l/e/n/leng3-20919.md#traducciones▓",
  "▓冷 (冷) [lěng] · Vocabulario relacionado▒l/e/n/leng3-20919.md#vocabulario-relacionado▓",
  "▓咖啡 (咖啡) [kāfēi]▒k/a/1/ka1-fei1.md▓",
  "▓咖啡 (咖啡) [kāfēi] · Frases de ejemplo▒k/a/1/ka1-fei1.md#frases-de-ejemplo▓",
  "▓咖啡 (咖啡) [kāfēi] · Traducciones▒k/a/1/ka1-fei1.md#traducciones▓",
  "▓咖啡 (咖啡) [kāfēi] · Vocabulario relacionado▒k/a/1/ka1-fei1.md#vocabulario-relacionado▓",
  "▓天氣 (天气) [tiānqì]▒t/i/a/tian1-qi4.md▓",
  "▓天氣 (天气) [tiānqì] · Frases de ejemplo▒t/i/a/tian1-qi4.md#frases-de-ejemplo▓",
  "▓天氣 (天气) [tiānqì] · Traducciones▒t/i/a/tian1-qi4.md#traducciones▓",
  "▓天氣 (天气) [tiānqì] · Vocabulario relacionado▒t/i/a/tian1-qi4.md#vocabulario-relacionado▓",
  "▓天氣是冷。▒t/i/a/tian1-qi4-shi4-leng3.md▓",
  "▓天氣是冷。 · Desglose▒t/i/a/tian1-qi4-shi4-leng3.md#desglose▓",
  "▓是 (是) [shì]▒s/h/i/shi4-26159.md▓",
  "▓是 (是) [shì] · Frases de ejemplo▒s/h/i/shi4-26159.md#frases-de-ejemplo▓",
  "▓是 (是) [shì] · Traducciones▒s/h/i/shi4-26159.md#traducciones▓",
  "▓是不是？ (是不是？) [shì bú shì?]▒s/h/i/shi4-bu2-shi4.md▓",
  "▓是不是？ (是不是？) [shì bú shì?] · Formas alternativas▒s/h/i/shi4-bu2-shi4.md#formas-alternativas▓",
  "▓是不是？ (是不是？) [shì bú shì?] · Frases de ejemplo▒s/h/i/shi4-bu2-shi4.md#frases-de-ejemplo▓",
  "▓棵 (棵) [kē]▒k/e/1/ke1-26869.md▓",
  "▓棵 (棵) [kē] · Traducciones▒k/e/1/ke1-26869.md#traducciones▓",
  "▓老師 (老师) [lǎoshī]▒l/a/o/lao3-shi1.md▓",
  "▓老師 (老师) [lǎoshī] · Frases de ejemplo▒l/a/o/lao3-shi1.md#frases-de-ejemplo▓",
  "▓老師 (老师) [lǎoshī] · Traducciones▒l/a/o/lao3-shi1.md#traducciones▓"
];
