let base = [
  "tomar alguien el tole [loc.coloq.] ¶ En <i>Vocabulario español</i>. ¶ https://jucardus.github.io/diccionarios/vocabulario/vocabulario.html#tomar-alguien-el-tole-loccoloq",
  "llovizna, lloviznar [sin.] ¶ En <i>Vocabulario español</i>. ¶ https://jucardus.github.io/diccionarios/vocabulario/vocabulario.html#lovizna-lloviznar-sin",
  "ímprobo, ba [adj.] ¶ En <i>Vocabulario español</i>. ¶ https://jucardus.github.io/diccionarios/vocabulario/vocabulario.html#%C3%ADmprobo-ba-adj",
  "garzo, za [adj.] ¶ En <i>Vocabulario español</i>. ¶ https://jucardus.github.io/diccionarios/vocabulario/vocabulario.html#garzo-za-adj",
  "extemporáneo [sin.] ¶ En <i>Vocabulario español</i>. ¶ https://jucardus.github.io/diccionarios/vocabulario/vocabulario.html#extempor%C3%A1neo-sin",
  "enconar [v.] ¶ En <i>Vocabulario español</i>. ¶ https://jucardus.github.io/diccionarios/vocabulario/vocabulario.html#enconar-v",
  "enconado [adj.] ¶ En <i>Vocabulario español</i>. ¶ https://jucardus.github.io/diccionarios/vocabulario/vocabulario.html#enconado-adj",
  "atisbo [sin.] ¶ En <i>Vocabulario español</i>. ¶ https://jucardus.github.io/diccionarios/vocabulario/vocabulario.html#atisbo-sin",
  "Preface ¶ Prefacio de <i>Charlie Codman's Cruise</i>, en <i>Traducciones al español</i>. ¶ https://jucardus.github.io/traducciones/ccc/prefacio/prefacio.html",
  "Charlie Codman's Cruise, a Story for Boys ¶ Parte de <i>Traducciones al español</i>. ¶ https://jucardus.github.io/traducciones/ccc/ccc.html",
  "Apotegmas ¶ Aforismos de mi autoría, parte de <i>Escritos varios</i>. ¶ https://jucardus.github.io/escritos/apotegmas/apotegmas.html",
  "Citas ¶ Frases célebres, aforismos, refranes, proverbios. Parte de <i>Escritos varios</i>. ¶ https://jucardus.github.io/escritos/citas/citas.html",
  "Vocabulario español ¶ Algunas palabras españolas seguidas de sus significados. ¶ https://jucardus.github.io/diccionarios/vocabulario/vocabulario.html",
  "in deference to [loc.] ¶ En el <i>Diccionario inglés-español</i>. En consideración a, por deferencia a, por respeto a. ¶ https://jucardus.github.io/diccionarios/ingles-espanol/i/in-deference-to/in-deference-to.html",
  "Diccionario inglés-español - I ¶ Entradas iniciadas en I en el diccionario inglés-español. ¶ https://jucardus.github.io/diccionarios/ingles-espanol/i/i.html",
  "Diccionario inglés-español ¶ Parte de <i>Diccionarios todos</i>. ¶ https://jucardus.github.io/diccionarios/ingles-espanol/ingles-espanol.html",
  "Traducciones al español ¶ Textos traducidos del inglés y del francés al español. ¶ https://jucardus.github.io/traducciones/traducciones.html",
  "Programación básica ¶ Bash, CSS, Blogger, JavaScript, Google Apps Script. ¶ https://jucardus.github.io/programacion/programacion.html",
  "Índice alfabético ¶ Todas las entradas y subpáginas de este sitio, en orden alfabético. ¶ https://jucardus.github.io/indices/alfabetico.html",
  "Escritos varios ¶ Apotegmas, cuentos, citas, poesía, reflexiones. ¶ https://jucardus.github.io/escritos/escritos.html",
  "Enlaces muchos ¶ Enlaces a sitios externos de interés ¶ https://jucardus.github.io/enlaces/enlaces.html",
  "Diccionarios todos ¶ Inglés-español, chino-español, nombres bíblicos, multilingüe ¶ https://jucardus.github.io/diccionarios/diccionarios.html",
  "Actividad reciente ¶ Las subpáginas y entradas más recientes de este sitio. ¶ https://jucardus.github.io/actividad/actividad.html",
  "Repositorio ¶ El repositorio de este sitio, con busca, descarga, copia y otras opciones de GitHub. ¶ https://jucardus.github.io/repo",
  "Inicio ¶ Página de inicio, con el contenido principal. ¶ https://jucardus.github.io/"
  ]
