let data = [
"的 / 的 // [de] of; ~'s (possessive particle); (used after an attribute)",  
"中 / 中 // [zhōng] middle; center; China",  
"國 / 国 // [guó] country; nation; state",  
"有 / 有 // [yǒu] have; there is; possess",  
"人 / 人 // [rén] person; people; human",  
"學 / 学 // [xué] study; learn; school",  
"一 / 一 // [yī] one; a single; whole",  
"年 / 年 // [nián] year; age; harvest",  
"大 / 大 // [dà] big; large; great",  
"不 / 不 // [bù] not; no; un-",  
"工 / 工 // [gōng] work; labor; industry",  
"公 / 公 // [gōng] public; common; duke",  
"是 / 是 // [shì] is; are; yes",  
"作 / 作 // [zuò] do; make; write",  
"經 / 经 // [jīng] pass through; manage; scripture",  
"市 / 市 // [shì] city; market; municipal",  
"應 / 应 // [yīng] should; ought to; respond",  
"區 / 区 // [qū] area; district; region",  
"為 / 为 // [wèi] for; because of; in order to",  
"在 / 在 // [zài] at; in; exist",
"歷 / 历 // [lì] to experience; calendar; to pass",  
"時 / 时 // [shí] time; hour; season",  
"台 / 台 // [tái] platform; stage; Taiwan",  
"徵 / 征 // [zhēng] to levy; to summon; evidence",  
"理 / 理 // [lǐ] reason; logic; to manage",  
"要 / 要 // [yào] to want; important; essential",  
"生 / 生 // [shēng] to be born; life; raw",  
"以 / 以 // [yǐ] by means of; in order to; with",  
"與 / 与 // [yǔ] and; to give; with",  
"新 / 新 // [xīn] new; freshly; newly",  
"司 / 司 // [sī] to take charge; department; company",  
"日 / 日 // [rì] sun; day; Japan",  
"發 / 发 // [fā] to issue; to send out; to develop",  
"之 / 之 // [zhī] of; this; him/her/it",  
"物 / 物 // [wù] thing; object; matter",  
"分 / 分 // [fēn] to divide; minute; part",  
"業 / 业 // [yè] business; profession; industry",  
"可 / 可 // [kě] can; may; approve",  
"會 / 会 // [huì] can; meeting; society",  
"我 / 我 // [wǒ] I; me; my",
];
