let data = [
"的 / 的 // [de] of; ~'s (possessive particle); indeed",  
"一 / 一 // [yī] one; a; single",  
"是 / 是 // [shì] to be; yes; this",  
"不 / 不 // [bù] not; no; un-",  
"了 / 了 // [le] (completed action marker); to finish; to understand",  
"在 / 在 // [zài] at; in; to exist",  
"人 / 人 // [rén] person; people; human",  
"有 / 有 // [yǒu] to have; there is; to exist",  
"我 / 我 // [wǒ] I; me; my",  
"他 / 他 // [tā] he; him; other",
"這 / 这 // [zhè] this; these; such",  
"個 / 个 // [gè] individual; measure word; piece",  
"們 / 们 // [men] (plural marker for pronouns); people; group",  
"中 / 中 // [zhōng] middle; center; China",  
"來 / 来 // [lái] to come; to arrive; future",  
"上 / 上 // [shàng] above; up; previous",  
"大 / 大 // [dà] big; large; great",  
"為 / 为 // [wèi] for; to; because of",  
"和 / 和 // [hé] and; harmony; peace",  
"國 / 国 // [guó] country; nation; state",
"地 / 地 // [dì] ground; earth; place",  
"到 / 到 // [dào] to arrive; to go to; to reach",  
"以 / 以 // [yǐ] by means of; in order to; according to",  
"说 / 说 // [shuō] to speak; to say; theory",  
"时 / 时 // [shí] time; hour; season",  
"要 / 要 // [yào] to want; important; will",  
"就 / 就 // [jiù] just; at once; then",  
"出 / 出 // [chū] to go out; to come out; to produce",  
"会 / 会 // [huì] can; meeting; society",  
"可 / 可 // [kě] can; may; but",  
"也 / 也 // [yě] also; too; as well",  
"你 / 你 // [nǐ] you; your; yourself",  
"对 / 对 // [duì] correct; to; towards",  
"生 / 生 // [shēng] to be born; life; raw",  
"能 / 能 // [néng] can; ability; energy",  
"而 / 而 // [ér] and; yet; but",  
"子 / 子 // [zǐ] child; son; seed",  
"那 / 那 // [nà] that; those; then",  
"得 / 得 // [dé] to obtain; to get; (structural particle)",  
"于 / 于 // [yú] in; at; to",
];
